In [1]:
from sklearn.impute import KNNImputer
import numpy as np

# Sample data with missing values
data = np.array([[1, 2, np.nan], [3, 4, 3], [7, 6, np.nan], [np.nan, 8, 9]])

# Initialize the KNNImputer with the number of neighbors
imputer = KNNImputer(n_neighbors=2)

# Perform imputation
imputed_data = imputer.fit_transform(data)

print(imputed_data)

[[1. 2. 6.]
 [3. 4. 3.]
 [7. 6. 6.]
 [5. 8. 9.]]


In [2]:
data

array([[ 1.,  2., nan],
       [ 3.,  4.,  3.],
       [ 7.,  6., nan],
       [nan,  8.,  9.]])